# Extended docker-compose.yml with more options
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robiul
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # For development, you might want to mount source code for hot reloading
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    #   - /app/.next
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
